// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Umbraco.Homework.API.Data;

namespace Umbraco.Homework.API.Migrations
{
    [DbContext(typeof(PrizeDrawDbContext))]
    [Migration("20210203181348_addSerialNumberDataTypeToPrizeDraw")]
    partial class addSerialNumberDataTypeToPrizeDraw
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Umbraco.Homework.API.Models.PrizeDrawEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("SerialNumberId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Submitted")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumberId");

                    b.ToTable("PrizeDrawEntries");
                });

            modelBuilder.Entity("Umbraco.Homework.API.Models.SerialNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Uses")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidUnitl")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SerialNumbers");
                });

            modelBuilder.Entity("Umbraco.Homework.API.Models.PrizeDrawEntry", b =>
                {
                    b.HasOne("Umbraco.Homework.API.Models.SerialNumber", "SerialNumber")
                        .WithMany()
                        .HasForeignKey("SerialNumberId");

                    b.Navigation("SerialNumber");
                });
#pragma warning restore 612, 618
        }
    }
}
